services:
  trees_everywhere:
    container_name: "trees_everywhere"
    build: .
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true