services:
  trees_everywhere:
    container_name: "trees_everywhere"
    build: .
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_trees:/var/lib/postgresql/data

volumes:
  postgres_trees: