# Generated by Django 5.1 on 2024-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_plantedtree_account_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='age',
        ),
    ]
